spring.application.name=OTPAuthenticator

spring.datasource.url=jdbc:mysql://localhost:3306/otp_authenticator_db
spring.datasource.username=appuser
spring.datasource.password=apppass

spring.docker.compose.lifecycle-management=start_only
